apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
type: Opaque
stringData:
  url: https://github.com/shart-cloud/devsecops-portfolio-template.git
  username: git
  password: bad-token
