apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-web
  namespace: kustomize-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-web
  template:
    metadata:
      labels:
        app: course-web
    spec:
      containers:
        - name: web
          image: nginx:1.27
          env:
            - name: APP_MODE
              value: dev
          ports:
            - containerPort: 80
