apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-ingress-app
  labels:
    app: jerry-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerry-ingress
  template:
    metadata:
      labels:
        app: jerry-ingress
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0.0
          args:
            - "-text=jerry-ingress-ok"
            - "-listen=:5678"
          ports:
            - containerPort: 5678
