apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jerry-web
spec:
  ingressClassName: nginx
  rules:
    - host: jery.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jerry-ingress-svc
                port:
                  number: 80
