apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: app
        image: nginx:1.25-alpine
        resources:
          requests:
            cpu: 800m      # Jerry's over-provisioned guess
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 1Gi
