apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jerry-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jerry-app
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: app
      minAllowed:
        cpu: 10m
        memory: 16Mi
      maxAllowed:
        cpu: 2
        memory: 2Gi
