apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    kubernetes.io/metadata.name: payments
---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    kubernetes.io/metadata.name: web
